#!/bin/bash
# Nablarch class count tool
# Counts Java type declarations across all repositories in the nablarch GitHub organization.
# Output: CSV / JSON / Markdown report under output/

set -euo pipefail

WORKDIR="${1:-/tmp/nablarch-classes}"
REPOS_DIR="$WORKDIR/repos"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
OUT_DIR="$SCRIPT_DIR/output"
mkdir -p "$REPOS_DIR" "$OUT_DIR"

if ! command -v gh >/dev/null 2>&1; then
  echo "ERROR: gh CLI is required." >&2
  exit 1
fi
if ! gh auth status >/dev/null 2>&1; then
  echo "ERROR: gh auth is not configured. Run 'gh auth login' first." >&2
  exit 1
fi

echo "[1/4] Listing nablarch organization repositories..."
gh repo list nablarch --limit 200 --json name --jq '.[].name' \
  > "$WORKDIR/repos.txt"
REPO_COUNT=$(wc -l < "$WORKDIR/repos.txt")
echo "  target repository count: $REPO_COUNT"

echo "[2/4] Shallow-cloning repositories (parallel=4, existing dirs skipped)..."
cat "$WORKDIR/repos.txt" | xargs -I{} -P 4 bash -c '
  target="'"$REPOS_DIR"'/{}"
  if [ ! -d "$target" ]; then
    gh repo clone "nablarch/{}" "$target" -- --depth 1 --quiet 2>/dev/null || true
  fi
'

echo "[3/4] Aggregating class counts..."
CSV="$OUT_DIR/class-count.csv"
echo "repo,classes,interfaces,enums,annotations,records,total_main,java_files_main,total_test,java_files_test" \
  > "$CSV"

# Regex patterns (line head, optional modifiers, capitalized identifier)
PAT_CLASS='^[[:space:]]*(public[[:space:]]+|protected[[:space:]]+|private[[:space:]]+)?(static[[:space:]]+)?(final[[:space:]]+|abstract[[:space:]]+)?class[[:space:]]+[A-Z]'
PAT_IFACE='^[[:space:]]*(public[[:space:]]+|protected[[:space:]]+|private[[:space:]]+)?(static[[:space:]]+)?interface[[:space:]]+[A-Z]'
PAT_ENUM='^[[:space:]]*(public[[:space:]]+|protected[[:space:]]+|private[[:space:]]+)?(static[[:space:]]+)?enum[[:space:]]+[A-Z]'
PAT_ANNO='^[[:space:]]*(public[[:space:]]+|protected[[:space:]]+|private[[:space:]]+)?@interface[[:space:]]+[A-Z]'
PAT_RECORD='^[[:space:]]*(public[[:space:]]+|protected[[:space:]]+|private[[:space:]]+)?(static[[:space:]]+)?record[[:space:]]+[A-Z]'

count_in_dir() {
  local dir="$1" pat="$2" n
  if [ -d "$dir" ]; then
    # grep returns 1 when no match; tolerate that under set -e
    n=$(grep -rE "$pat" "$dir" --include='*.java' 2>/dev/null | wc -l || true)
    echo "${n:-0}"
  else
    echo 0
  fi
}

count_files() {
  local dir="$1" n
  if [ -d "$dir" ]; then
    n=$(find "$dir" -name '*.java' 2>/dev/null | wc -l || true)
    echo "${n:-0}"
  else
    echo 0
  fi
}

for repo_dir in "$REPOS_DIR"/*/; do
  [ -d "$repo_dir" ] || continue
  repo=$(basename "$repo_dir")
  src="$repo_dir/src/main/java"
  tst="$repo_dir/src/test/java"

  [ -d "$src" ] || continue

  classes=$(count_in_dir "$src" "$PAT_CLASS")
  interfaces=$(count_in_dir "$src" "$PAT_IFACE")
  enums=$(count_in_dir "$src" "$PAT_ENUM")
  annos=$(count_in_dir "$src" "$PAT_ANNO")
  records=$(count_in_dir "$src" "$PAT_RECORD")
  total=$((classes + interfaces + enums + annos + records))
  files=$(count_files "$src")

  tst_classes=$(count_in_dir "$tst" "$PAT_CLASS")
  tst_files=$(count_files "$tst")

  echo "$repo,$classes,$interfaces,$enums,$annos,$records,$total,$files,$tst_classes,$tst_files" \
    >> "$CSV"
done

echo "[4/4] Generating JSON and Markdown report..."

# CSV -> JSON (awk)
JSON="$OUT_DIR/class-count.json"
awk -F',' '
  NR==1 {
    for (i=1; i<=NF; i++) headers[i]=$i
    print "["
    next
  }
  {
    if (NR > 2) print ","
    printf "  {"
    for (i=1; i<=NF; i++) {
      if (i > 1) printf ", "
      if (i == 1) {
        printf "\"%s\": \"%s\"", headers[i], $i
      } else {
        printf "\"%s\": %s", headers[i], $i
      }
    }
    printf "}"
  }
  END { print ""; print "]" }
' "$CSV" > "$JSON"

# CSV -> Markdown report
REPORT="$OUT_DIR/REPORT.md"
{
  echo "# Nablarch Class Count Report"
  echo ""
  echo "Generated by \`tools/count-classes/run.sh\` against the nablarch GitHub organization."
  echo ""
  echo "## Summary"
  echo ""
  awk -F',' '
    NR>1 {
      repos++
      c+=$2; i+=$3; e+=$4; a+=$5; r+=$6; t+=$7; f+=$8; tt+=$9; tf+=$10
    }
    END {
      printf "- Repositories with src/main/java: %d\n", repos
      printf "- Total classes: %d\n", c
      printf "- Total interfaces: %d\n", i
      printf "- Total enums: %d\n", e
      printf "- Total annotations: %d\n", a
      printf "- Total records: %d\n", r
      printf "- Grand total (main): %d\n", t
      printf "- Java files (main): %d\n", f
      printf "- Test classes: %d\n", tt
      printf "- Java files (test): %d\n", tf
    }
  ' "$CSV"
  echo ""
  echo "## Per-Repository Breakdown"
  echo ""
  echo "| Repository | Classes | Interfaces | Enums | Annotations | Records | Total (main) | Java files (main) | Test classes | Java files (test) |"
  echo "|------------|--------:|-----------:|------:|------------:|--------:|-------------:|------------------:|-------------:|------------------:|"
  awk -F',' 'NR>1 {
    printf "| %s | %s | %s | %s | %s | %s | %s | %s | %s | %s |\n", $1,$2,$3,$4,$5,$6,$7,$8,$9,$10
  }' "$CSV" | sort -t'|' -k8 -n -r
  echo ""
  echo "## Top 10 Repositories by total_main"
  echo ""
  echo "| Rank | Repository | total_main |"
  echo "|-----:|------------|----------:|"
  awk -F',' 'NR>1 {print $7","$1}' "$CSV" | sort -t',' -k1 -n -r | head -10 | awk -F',' '{ printf "| %d | %s | %s |\n", NR, $2, $1 }'
  echo ""
  echo "## Visualization Estimates (node count assumptions)"
  echo ""
  awk -F',' '
    NR>1 { total_main += $7; classes += $2; interfaces += $3 }
    END {
      printf "- Including all type kinds (classes + interfaces + enums + annotations + records, main only): **%d nodes**\n", total_main
      printf "- Classes only (main): **%d nodes**\n", classes
      printf "- Classes + interfaces only (main): **%d nodes**\n", classes + interfaces
    }
  ' "$CSV"
  echo ""
  echo "_Note: inner types (nested / anonymous) are not counted in the per-line regex._"
} > "$REPORT"

echo "Done."
echo "  CSV:    $CSV"
echo "  JSON:   $JSON"
echo "  REPORT: $REPORT"
